/* AUTO-GENERATED: DO NOT EDIT */
/* generated by: scripts/generate_genpack_error_codes_bindings.py --write */

export const X07_GENPACK_E_BUNDLE_SHAPE_INVALID = "X07_GENPACK_E_BUNDLE_SHAPE_INVALID" as const;
export const X07_GENPACK_E_CACHE_IO = "X07_GENPACK_E_CACHE_IO" as const;
export const X07_GENPACK_E_DIR_MISSING_ARTIFACT = "X07_GENPACK_E_DIR_MISSING_ARTIFACT" as const;
export const X07_GENPACK_E_DIR_READ_FAILED = "X07_GENPACK_E_DIR_READ_FAILED" as const;
export const X07_GENPACK_E_GRAMMAR_BUNDLE_JSON_PARSE = "X07_GENPACK_E_GRAMMAR_BUNDLE_JSON_PARSE" as const;
export const X07_GENPACK_E_GRAMMAR_BUNDLE_VERSION_MISMATCH = "X07_GENPACK_E_GRAMMAR_BUNDLE_VERSION_MISMATCH" as const;
export const X07_GENPACK_E_HASH_MISMATCH = "X07_GENPACK_E_HASH_MISMATCH" as const;
export const X07_GENPACK_E_MATERIALIZE_IO = "X07_GENPACK_E_MATERIALIZE_IO" as const;
export const X07_GENPACK_E_SCHEMA_JSON_PARSE = "X07_GENPACK_E_SCHEMA_JSON_PARSE" as const;
export const X07_GENPACK_E_SCHEMA_VERSION_MISMATCH = "X07_GENPACK_E_SCHEMA_VERSION_MISMATCH" as const;
export const X07_GENPACK_E_SEMANTIC_SUPPLEMENT_VERSION_MISMATCH = "X07_GENPACK_E_SEMANTIC_SUPPLEMENT_VERSION_MISMATCH" as const;
export const X07_GENPACK_E_STDOUT_NOT_UTF8 = "X07_GENPACK_E_STDOUT_NOT_UTF8" as const;
export const X07_GENPACK_E_SUBPROCESS_FAILED = "X07_GENPACK_E_SUBPROCESS_FAILED" as const;
export const X07_GENPACK_E_SUBPROCESS_TIMEOUT = "X07_GENPACK_E_SUBPROCESS_TIMEOUT" as const;
export const X07_GENPACK_E_VARIANT_MISSING = "X07_GENPACK_E_VARIANT_MISSING" as const;
export const X07_GENPACK_E_X07_NOT_FOUND = "X07_GENPACK_E_X07_NOT_FOUND" as const;

export const ALL_CODES = [
  X07_GENPACK_E_BUNDLE_SHAPE_INVALID,
  X07_GENPACK_E_CACHE_IO,
  X07_GENPACK_E_DIR_MISSING_ARTIFACT,
  X07_GENPACK_E_DIR_READ_FAILED,
  X07_GENPACK_E_GRAMMAR_BUNDLE_JSON_PARSE,
  X07_GENPACK_E_GRAMMAR_BUNDLE_VERSION_MISMATCH,
  X07_GENPACK_E_HASH_MISMATCH,
  X07_GENPACK_E_MATERIALIZE_IO,
  X07_GENPACK_E_SCHEMA_JSON_PARSE,
  X07_GENPACK_E_SCHEMA_VERSION_MISMATCH,
  X07_GENPACK_E_SEMANTIC_SUPPLEMENT_VERSION_MISMATCH,
  X07_GENPACK_E_STDOUT_NOT_UTF8,
  X07_GENPACK_E_SUBPROCESS_FAILED,
  X07_GENPACK_E_SUBPROCESS_TIMEOUT,
  X07_GENPACK_E_VARIANT_MISSING,
  X07_GENPACK_E_X07_NOT_FOUND,
] as const;

export type GenpackErrorCode = (typeof ALL_CODES)[number];

export type GenpackErrorSeverity = "error" | "warn";

export const CODE_DOCS: Record<GenpackErrorCode, {
  severity: GenpackErrorSeverity;
  retryable: boolean;
  summary: string;
  dataFields: string[];
  hints: string[];
}> = {
  X07_GENPACK_E_BUNDLE_SHAPE_INVALID: {
    severity: "error",
    retryable: false,
    summary: "Grammar bundle JSON did not have the required fields or had invalid types.",
    dataFields: ["missing_fields"],
    hints: ["Treat this as an x07 tooling regression if the bundle schema_version appears correct.","Capture the full bundle JSON and file an issue."],
  },
  X07_GENPACK_E_CACHE_IO: {
    severity: "error",
    retryable: true,
    summary: "Failed to read/write the SDK cache directory.",
    dataFields: ["cache_dir","io_error"],
    hints: ["Disable caching or choose a writable cache directory."],
  },
  X07_GENPACK_E_DIR_MISSING_ARTIFACT: {
    severity: "error",
    retryable: false,
    summary: "Directory source is missing one or more required artifacts.",
    dataFields: ["dir","missing_paths"],
    hints: ["Recreate the directory using: x07 ast grammar --cfg --out-dir <DIR>."],
  },
  X07_GENPACK_E_DIR_READ_FAILED: {
    severity: "error",
    retryable: true,
    summary: "Failed to read an artifact from the directory source.",
    dataFields: ["path","io_error"],
    hints: ["Verify file permissions and that the artifact files are not being concurrently modified."],
  },
  X07_GENPACK_E_GRAMMAR_BUNDLE_JSON_PARSE: {
    severity: "error",
    retryable: false,
    summary: "Failed to parse grammar bundle output as JSON.",
    dataFields: ["argv","stdout_prefix"],
    hints: ["Ensure x07 ast grammar --cfg prints raw JSON only (no logs).","If you see mixed output, ensure stderr/stdout are not being merged."],
  },
  X07_GENPACK_E_GRAMMAR_BUNDLE_VERSION_MISMATCH: {
    severity: "error",
    retryable: false,
    summary: "Grammar bundle output did not match the expected bundle schema_version.",
    dataFields: ["expected","actual"],
    hints: ["Pin x07 toolchain version or upgrade the SDK to match the new bundle contract."],
  },
  X07_GENPACK_E_HASH_MISMATCH: {
    severity: "error",
    retryable: false,
    summary: "Artifact content hash did not match the declared sha256 in the bundle/manifest.",
    dataFields: ["path","expected_sha256","actual_sha256"],
    hints: ["Assume artifact corruption; regenerate artifacts with x07 and avoid editing outputs."],
  },
  X07_GENPACK_E_MATERIALIZE_IO: {
    severity: "error",
    retryable: true,
    summary: "Failed to materialize generation-pack artifacts to an output directory.",
    dataFields: ["out_dir","io_error"],
    hints: ["Verify the output directory is writable.","If running concurrently, use distinct output directories."],
  },
  X07_GENPACK_E_SCHEMA_JSON_PARSE: {
    severity: "error",
    retryable: false,
    summary: "Failed to parse JSON Schema output as JSON.",
    dataFields: ["argv","stdout_prefix"],
    hints: ["Ensure x07 ast schema --json-schema prints raw JSON schema only (no logs).","If you see mixed output, ensure stderr/stdout are not being merged."],
  },
  X07_GENPACK_E_SCHEMA_VERSION_MISMATCH: {
    severity: "error",
    retryable: false,
    summary: "Schema output did not match the expected schema contract.",
    dataFields: ["expected","actual"],
    hints: ["Pin x07 toolchain version or disable strict checks only if you control both sides.","Regenerate or upgrade the SDK if x07 changed the schema contract."],
  },
  X07_GENPACK_E_SEMANTIC_SUPPLEMENT_VERSION_MISMATCH: {
    severity: "error",
    retryable: false,
    summary: "Semantic supplement schema_version did not match the expected contract.",
    dataFields: ["expected","actual"],
    hints: ["Upgrade the SDK if x07 bumped the semantic supplement contract."],
  },
  X07_GENPACK_E_STDOUT_NOT_UTF8: {
    severity: "error",
    retryable: false,
    summary: "The x07 subprocess stdout was not valid UTF-8.",
    dataFields: ["argv"],
    hints: ["This indicates toolchain corruption or a bug in x07 output emission.","Run the command manually and file an issue with the raw bytes if possible."],
  },
  X07_GENPACK_E_SUBPROCESS_FAILED: {
    severity: "error",
    retryable: true,
    summary: "The x07 subprocess returned a non-zero exit code.",
    dataFields: ["argv","exit_code","stderr"],
    hints: ["Inspect stderr for the underlying x07 error.","If this happens only on one machine, verify the x07 toolchain install and permissions."],
  },
  X07_GENPACK_E_SUBPROCESS_TIMEOUT: {
    severity: "error",
    retryable: true,
    summary: "The x07 subprocess did not complete before the timeout.",
    dataFields: ["argv","timeout_s"],
    hints: ["Increase the timeout in GenpackClient options.","If x07 is hanging, run the command manually to reproduce and capture logs."],
  },
  X07_GENPACK_E_VARIANT_MISSING: {
    severity: "error",
    retryable: false,
    summary: "Requested grammar variant was not present in the grammar bundle.",
    dataFields: ["variant","available_variants"],
    hints: ["Use an available variant from the bundle.","If you expected it to exist, verify x07 tooling version."],
  },
  X07_GENPACK_E_X07_NOT_FOUND: {
    severity: "error",
    retryable: false,
    summary: "Could not locate the x07 executable.",
    dataFields: ["x07_path","path_env"],
    hints: ["Install x07 and ensure it is available on PATH.","Or pass an explicit x07Path (SDK option) pointing to the x07 binary."],
  },
};
