use crate::os_policy::{NetHost, Policy};

fn bool_env(v: bool) -> &'static str {
    if v {
        "1"
    } else {
        "0"
    }
}

fn encode_allow_hosts(hosts: &[NetHost]) -> String {
    let mut out = Vec::new();
    for h in hosts {
        let ports = h
            .ports
            .iter()
            .map(|p| p.to_string())
            .collect::<Vec<_>>()
            .join(",");
        out.push(format!("{}:{}", h.host.trim(), ports));
    }
    out.join(";")
}

pub fn policy_to_env(policy: &Policy) -> Vec<(String, String)> {
    vec![
        (
            "X07_OS_FS".to_string(),
            bool_env(policy.fs.enabled).to_string(),
        ),
        (
            "X07_OS_NET".to_string(),
            bool_env(policy.net.enabled).to_string(),
        ),
        (
            "X07_OS_DB".to_string(),
            bool_env(policy.db.enabled).to_string(),
        ),
        (
            "X07_OS_ENV".to_string(),
            bool_env(policy.env.enabled).to_string(),
        ),
        (
            "X07_OS_TIME".to_string(),
            bool_env(policy.time.enabled).to_string(),
        ),
        (
            "X07_OS_PROC".to_string(),
            bool_env(policy.process.enabled).to_string(),
        ),
        (
            "X07_OS_THREADS".to_string(),
            bool_env(policy.threads.enabled).to_string(),
        ),
        (
            "X07_OS_THREADS_MAX_WORKERS".to_string(),
            policy.threads.max_workers.to_string(),
        ),
        (
            "X07_OS_THREADS_MAX_BLOCKING".to_string(),
            policy.threads.max_blocking.to_string(),
        ),
        (
            "X07_OS_THREADS_MAX_QUEUE".to_string(),
            policy.threads.max_queue.to_string(),
        ),
        (
            "X07_OS_DENY_HIDDEN".to_string(),
            bool_env(policy.fs.deny_hidden).to_string(),
        ),
        (
            "X07_OS_FS_READ_ROOTS".to_string(),
            policy.fs.read_roots.join(";"),
        ),
        (
            "X07_OS_FS_WRITE_ROOTS".to_string(),
            policy.fs.write_roots.join(";"),
        ),
        (
            "X07_OS_FS_ALLOW_SYMLINKS".to_string(),
            bool_env(policy.fs.allow_symlinks).to_string(),
        ),
        (
            "X07_OS_FS_ALLOW_MKDIR".to_string(),
            bool_env(policy.fs.allow_mkdir).to_string(),
        ),
        (
            "X07_OS_FS_ALLOW_REMOVE".to_string(),
            bool_env(policy.fs.allow_remove).to_string(),
        ),
        (
            "X07_OS_FS_ALLOW_RENAME".to_string(),
            bool_env(policy.fs.allow_rename).to_string(),
        ),
        (
            "X07_OS_FS_ALLOW_WALK".to_string(),
            bool_env(policy.fs.allow_walk).to_string(),
        ),
        (
            "X07_OS_FS_ALLOW_GLOB".to_string(),
            bool_env(policy.fs.allow_glob).to_string(),
        ),
        (
            "X07_OS_FS_MAX_READ_BYTES".to_string(),
            policy.fs.max_read_bytes.to_string(),
        ),
        (
            "X07_OS_FS_MAX_WRITE_BYTES".to_string(),
            policy.fs.max_write_bytes.to_string(),
        ),
        (
            "X07_OS_FS_MAX_ENTRIES".to_string(),
            policy.fs.max_entries.to_string(),
        ),
        (
            "X07_OS_FS_MAX_DEPTH".to_string(),
            policy.fs.max_depth.to_string(),
        ),
        (
            "X07_OS_ENV_ALLOW_KEYS".to_string(),
            policy.env.allow_keys.join(";"),
        ),
        (
            "X07_OS_ENV_DENY_KEYS".to_string(),
            policy.env.deny_keys.join(";"),
        ),
        (
            "X07_OS_DB_SQLITE".to_string(),
            bool_env(policy.db.drivers.sqlite).to_string(),
        ),
        (
            "X07_OS_DB_PG".to_string(),
            bool_env(policy.db.drivers.postgres).to_string(),
        ),
        (
            "X07_OS_DB_MYSQL".to_string(),
            bool_env(policy.db.drivers.mysql).to_string(),
        ),
        (
            "X07_OS_DB_REDIS".to_string(),
            bool_env(policy.db.drivers.redis).to_string(),
        ),
        (
            "X07_OS_DB_SQLITE_READONLY_ONLY".to_string(),
            bool_env(policy.db.sqlite.readonly_only).to_string(),
        ),
        (
            "X07_OS_DB_SQLITE_ALLOW_CREATE".to_string(),
            bool_env(policy.db.sqlite.allow_create).to_string(),
        ),
        (
            "X07_OS_DB_SQLITE_ALLOW_IN_MEMORY".to_string(),
            bool_env(policy.db.sqlite.allow_in_memory).to_string(),
        ),
        (
            "X07_OS_DB_SQLITE_ALLOW_PATHS".to_string(),
            policy.db.sqlite.allow_paths.join(";"),
        ),
        (
            "X07_OS_DB_MAX_LIVE_CONNS".to_string(),
            policy.db.max_live_conns.to_string(),
        ),
        (
            "X07_OS_DB_MAX_QUERIES".to_string(),
            policy.db.max_queries.to_string(),
        ),
        (
            "X07_OS_DB_MAX_CONNECT_TIMEOUT_MS".to_string(),
            policy.db.connect_timeout_ms.to_string(),
        ),
        (
            "X07_OS_DB_MAX_QUERY_TIMEOUT_MS".to_string(),
            policy.db.query_timeout_ms.to_string(),
        ),
        (
            "X07_OS_DB_MAX_SQL_BYTES".to_string(),
            policy.db.max_sql_bytes.to_string(),
        ),
        (
            "X07_OS_DB_MAX_ROWS".to_string(),
            policy.db.max_rows.to_string(),
        ),
        (
            "X07_OS_DB_MAX_RESP_BYTES".to_string(),
            policy.db.max_resp_bytes.to_string(),
        ),
        (
            "X07_OS_DB_NET_ALLOW_DNS".to_string(),
            policy.db.net.allow_dns.join(";"),
        ),
        (
            "X07_OS_DB_NET_ALLOW_CIDRS".to_string(),
            policy.db.net.allow_cidrs.join(";"),
        ),
        (
            "X07_OS_DB_NET_ALLOW_PORTS".to_string(),
            policy
                .db
                .net
                .allow_ports
                .iter()
                .map(|p| p.to_string())
                .collect::<Vec<_>>()
                .join(","),
        ),
        (
            "X07_OS_DB_NET_REQUIRE_TLS".to_string(),
            bool_env(policy.db.net.require_tls).to_string(),
        ),
        (
            "X07_OS_DB_NET_REQUIRE_VERIFY".to_string(),
            bool_env(policy.db.net.require_verify).to_string(),
        ),
        (
            "X07_OS_TIME_ALLOW_WALL_CLOCK".to_string(),
            bool_env(policy.time.allow_wall_clock).to_string(),
        ),
        (
            "X07_OS_TIME_ALLOW_MONOTONIC".to_string(),
            bool_env(policy.time.allow_monotonic).to_string(),
        ),
        (
            "X07_OS_TIME_ALLOW_SLEEP".to_string(),
            bool_env(policy.time.allow_sleep).to_string(),
        ),
        (
            "X07_OS_TIME_MAX_SLEEP_MS".to_string(),
            policy.time.max_sleep_ms.to_string(),
        ),
        (
            "X07_OS_TIME_ALLOW_LOCAL_TZID".to_string(),
            bool_env(policy.time.allow_local_tzid).to_string(),
        ),
        (
            "X07_OS_PROC_ALLOW_EXIT".to_string(),
            bool_env(policy.process.allow_exit).to_string(),
        ),
        (
            "X07_OS_PROC_ALLOW_SPAWN".to_string(),
            bool_env(policy.process.allow_spawn).to_string(),
        ),
        (
            "X07_OS_PROC_MAX_LIVE".to_string(),
            policy.process.max_live.to_string(),
        ),
        (
            "X07_OS_PROC_MAX_SPAWNS".to_string(),
            policy.process.max_spawns.to_string(),
        ),
        (
            "X07_OS_PROC_MAX_EXE_BYTES".to_string(),
            policy.process.max_exe_bytes.to_string(),
        ),
        (
            "X07_OS_PROC_MAX_ARGS".to_string(),
            policy.process.max_args.to_string(),
        ),
        (
            "X07_OS_PROC_MAX_ARG_BYTES".to_string(),
            policy.process.max_arg_bytes.to_string(),
        ),
        (
            "X07_OS_PROC_MAX_ENV".to_string(),
            policy.process.max_env.to_string(),
        ),
        (
            "X07_OS_PROC_MAX_ENV_KEY_BYTES".to_string(),
            policy.process.max_env_key_bytes.to_string(),
        ),
        (
            "X07_OS_PROC_MAX_ENV_VAL_BYTES".to_string(),
            policy.process.max_env_val_bytes.to_string(),
        ),
        (
            "X07_OS_PROC_MAX_RUNTIME_MS".to_string(),
            policy.process.max_runtime_ms.to_string(),
        ),
        (
            "X07_OS_PROC_MAX_STDOUT_BYTES".to_string(),
            policy.process.max_stdout_bytes.to_string(),
        ),
        (
            "X07_OS_PROC_MAX_STDERR_BYTES".to_string(),
            policy.process.max_stderr_bytes.to_string(),
        ),
        (
            "X07_OS_PROC_MAX_TOTAL_BYTES".to_string(),
            policy.process.max_total_bytes.to_string(),
        ),
        (
            "X07_OS_PROC_MAX_STDIN_BYTES".to_string(),
            policy.process.max_stdin_bytes.to_string(),
        ),
        (
            "X07_OS_PROC_KILL_ON_DROP".to_string(),
            bool_env(policy.process.kill_on_drop).to_string(),
        ),
        (
            "X07_OS_PROC_KILL_TREE".to_string(),
            bool_env(policy.process.kill_tree).to_string(),
        ),
        (
            "X07_OS_PROC_ALLOW_CWD".to_string(),
            bool_env(policy.process.allow_cwd).to_string(),
        ),
        (
            "X07_OS_PROC_ALLOW_CWD_ROOTS".to_string(),
            policy.process.allow_cwd_roots.join(";"),
        ),
        (
            "X07_OS_PROC_ALLOW_EXEC".to_string(),
            bool_env(policy.process.allow_exec).to_string(),
        ),
        (
            "X07_OS_PROC_ALLOW_EXECS".to_string(),
            policy.process.allow_execs.join(";"),
        ),
        (
            "X07_OS_PROC_ALLOW_EXEC_PREFIXES".to_string(),
            policy.process.allow_exec_prefixes.join(";"),
        ),
        (
            "X07_OS_PROC_ALLOW_ARGS_REGEX_LITE".to_string(),
            policy.process.allow_args_regex_lite.join(";"),
        ),
        (
            "X07_OS_PROC_ALLOW_ENV_KEYS".to_string(),
            policy.process.allow_env_keys.join(";"),
        ),
        (
            "X07_OS_NET_ALLOW_TCP".to_string(),
            bool_env(policy.net.allow_tcp).to_string(),
        ),
        (
            "X07_OS_NET_ALLOW_UDP".to_string(),
            bool_env(policy.net.allow_udp).to_string(),
        ),
        (
            "X07_OS_NET_ALLOW_DNS".to_string(),
            bool_env(policy.net.allow_dns).to_string(),
        ),
        (
            "X07_OS_NET_ALLOW_HOSTS".to_string(),
            encode_allow_hosts(&policy.net.allow_hosts),
        ),
    ]
}
