pub mod ast;
pub mod builtin_modules;
pub mod c_emit;
pub mod cli_specrows;
pub mod compat;
pub mod compile;
pub mod contracts_elab;
pub mod diagnostics;
pub mod enums;
pub mod generics;
pub mod guide;
pub mod json_patch;
pub mod language;
pub mod lint;
pub(crate) mod mem_provenance;
pub mod module_source;
pub mod native;
pub mod optimize;
pub mod program;
pub mod project;
pub mod records;
pub mod stream_pipe;
pub mod suggest;
pub mod typecheck;
pub mod types;
pub mod validate;
pub mod wasm_emit;
pub mod world_config;
pub mod x07ast;
pub mod x07text;

pub const X07C_VERSION: &str = env!("CARGO_PKG_VERSION");

mod fingerprint;
pub mod unify;
